info:
  namespace: sweetmail
items:
  mail_back:
    material: PAPER
    generate: true
    model_id: 8731
    textures:
      - item/back
  mail_pageup:
    material: PAPER
    generate: true
    model_id: 8732
    textures:
      - item/page_up
  mail_pagedown:
    material: PAPER
    generate: true
    model_id: 8733
    textures:
      - item/page_down
