name: SweetMail
version: '${version}'
main: top.mrxiaom.sweetmail.SweetMail
api-version: 1.13
softdepend:
  - Vault
  - PlayerPoints
  - PlaceholderAPI
  - MythicMobs
  - ItemsAdder
  - NBTAPI
authors: [ MrXiaoM ]
commands:
  sweetmail:
    description: SweetMail main command.
    aliases: [sm, mail]

permissions:
  sweetmail.icon.default:
    default: true
  sweetmail.price.default:
    default: true
  sweetmail.outdate.default:
    default: true
  sweetmail.draft.outdate.default:
    default: true
  sweetmail.attachment.item:
    default: true
